### ISSUE TITLE
r2skel script works only when symlinked

### ISSUE THREAD

**Issue by satk0** [radareorg/radare2-skel#1]
## Description

Adding the possibility to run the bash `r2skel` script from the repo directory directly would be great. Right now I need to make a symbolic link to another directory to properly run it.

I could make a PR that implements this :smiley:

**Comment by trufae** [comment]
Go for the pr :) right now it works via r2pm -r r2skel.. but the more flexible the better

**Comment by satk0** [comment]
Allright. r2pm is like a magic key to run anything in this repo. I used it for meson building and it worked out perfectly.
